### ISSUE TITLE
No VGA bitmap font in output list

### ISSUE THREAD

**Issue by jpka-** [qtmlabs/xlsfonts#1]
Hello. I am working with bitmap/fixed fonts. I have _VGA_ font (https://aur.archlinux.org/univga.git) which works with X11 apps, and lists here:
**fc-list | grep -iF vga
/usr/share/fonts/local/u_vga16.otb: VGA:style=Regular**
But this not work:
**./xlsfonts | grep -iF vga**
 shows nothing.
Other bitmap fonts like _xos4 Terminus_, listed exactly correctly with _xlsfonts_.
Is this possible to fix?
I use XFCE and Archlinux, version of _xlsfonts_ is 1.0.8.
P.S. Sorry to report here but not at required (freedesktop's) place: i can't open issue there.
Thanks.

**Comment by msizanoen1** [comment]
Hello,

This is not the official upstream repository for xlsfonts and if you are unable to report it on freedesktop's gitlab then there's nothing we can do for you.

Thanks for your understanding.
